Updated documentation for Allow requests from global Azure datacenters or other sources within Azure
MicrosoftDocs/azure-databases-docs pull request #59
Opened 2024-09-27 17:40 UTC by YungtonMicrosoft

Updated how-to-configure-firewall.md to add a note about publicNetworkAccess disablement and how it takes precedence over all other firewall rules

2024-09-27 20:31 UTC, Jak-MS commented
@iriaosara 
Can you review the proposed changes? 

**Important**: When the changes are ready for publication, adding a `#sign-off` comment is the best way to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

2024-09-30 12:51 UTC, iriaosara approved these changes

2024-09-30 12:54 UTC, iriaosara requested changes
Fix the links by removing the "en-us"

2024-09-30 16:01 UTC, Jak-MS commented on articles/cosmos-db/how-to-configure-firewall.md
> +> Setting publicNetworkAccess to Disabled takes precedence over this **Accept connection from within Azure datacenters** option. See [blocking-public-network-access-during-account-creation](https://l
```suggestion
> Setting publicNetworkAccess to Disabled takes precedence over this **Accept connection from within Azure datacenters** option. See [blocking-public-network-access-during-account-creation](/azure/cosmos-db/how-to-configure-private-endpoints?tabs=arm-bicep#blocking-public-network-access-during-account-creation)
```

2024-09-30 16:06 UTC, merged